# NASA almond: nominal meshes and the admissible vector-field perturbation.
#
# GEOMETRY. Woo, Wang, Schuh & Sanders, IEEE Antennas Propag. Mag. 35(1),
# 84-89, 1993. Total length d = 9.936 in = 0.252374 m. The two nominal
# meshes are SHIPPED with the repository (data/almond/), not meshed here:
# they are built by a deterministic arc-length-graded parametric mesher,
# scripts/../data/almond is written by the Python module almond/almond.py in
# the manuscript repository, and shipping them keeps gmsh -- which is not
# reproducible across sessions -- out of the reproduction path entirely, for
# the same reason as the sphere and Fichera meshes (see p28).
#
# PERTURBATION. The deformation is the admissible class of Section 3.1,
#
#     T(x) = x + eps * V(x),        V : R^3 -> R^3 smooth,
#
# NOT a displacement along surface normals. V is a vector-valued random
# Fourier feature expansion of a squared-exponential covariance,
#
#     V(x) = scale * chi(x) * sqrt(2/M) * sum_k a_k cos(w_k . x + b_k),
#
# with (w_k, b_k, a_k) drawn once, exported as numbers, and read here. The
# field is a function of POSITION, so nothing depends on vertex ordering and
# the same parameter file drives the lambda/12 and lambda/20 meshes
# identically. `scale` fixes max|V| = 1 over a dense reference sampling of
# the nominal surface, so the level `eps` IS the maximum displacement, in
# metres, to within the discretisation of that reference set.
#
# chi is a C^1 cutoff that vanishes identically within `dead`*d of the sharp
# tip and rises to 1 over the following `ramp`*d (case T); for case U it is
# absent and the tip moves with its neighbourhood.
#
# INJECTIVITY. T is injective on any convex set whenever eps*sup|DV|_2 < 1.
# The exported index carries sup|DV|_2, evaluated on a refined grid over the
# bounding box of the nominal surface, and the amplitude ladder in
# data/almond/levels.csv is chosen so that eps*sup|DV| <= 0.5 for every
# sample at the primary correlation length. Validity is therefore certified
# in advance rather than discovered: the driver re-checks the certificate and
# ERRORS if a sample violates it. No sample is ever silently rejected.

using CompScienceMeshes
using DrWatson
using DelimitedFiles
using LinearAlgebra

const ALMOND_D = 0.2523744                 # 9.936 in, in metres
const ALMOND_LAMBDA = ALMOND_D / 3         # electrical size 3 lambda
const ALMOND_KAPPA = 2pi / ALMOND_LAMBDA
const ALMOND_HALF_THICK = 0.064444 * ALMOND_D   # z semi-axis at the seam

almond_dir() = projectdir("data", "almond")

"""
    almond_mesh(name)

Load a shipped nominal almond mesh. `name` is "almond_lam12" or
"almond_lam20". The CSV pair is preferred (it is the format p28 already uses
for the sphere and Fichera meshes); the Gmsh file beside it is a fallback and
a human-readable copy.
"""
function almond_mesh(name::AbstractString)
    dir = almond_dir()
    vfile = joinpath(dir, name * "_verts.csv")
    ffile = joinpath(dir, name * "_faces.csv")
    if isfile(vfile) && isfile(ffile)
        Vm = readdlm(vfile, ',', Float64)
        Fm = readdlm(ffile, ',', Int)
        verts = [point(Vm[i, 1], Vm[i, 2], Vm[i, 3]) for i in axes(Vm, 1)]
        faces = try
            [CompScienceMeshes.index(Fm[i, 1], Fm[i, 2], Fm[i, 3])
             for i in axes(Fm, 1)]
        catch err
            @warn "CompScienceMeshes.index unavailable ($err); falling back " *
                  "to the Gmsh reader"
            nothing
        end
        if faces !== nothing
            return Mesh(verts, faces)
        end
    end
    mshfile = joinpath(dir, name * ".msh")
    isfile(mshfile) || error("no almond mesh '$name' under $dir; run the " *
                             "export step first (see README_almond.md)")
    return CompScienceMeshes.read_gmsh_mesh(mshfile)
end

"""
    almond_signed_volume(Γ)

Enclosed volume by the divergence theorem; negative means inward-facing.
"""
function almond_signed_volume(Γ)
    vol = 0.0
    for f in Γ.faces
        a, b, c = Γ.vertices[f[1]], Γ.vertices[f[2]], Γ.vertices[f[3]]
        vol += dot(a, cross(b, c)) / 6
    end
    return vol
end

"""
    almond_orient(Γ)

Return the mesh consistently oriented and facing outward.

A POSITIVE ENCLOSED VOLUME IS NOT ENOUGH. `buffachristiansen` asserts
`CompScienceMeshes.isoriented`, which demands that every interior edge be
traversed in opposite directions by its two faces. A ring mesher can leave a
handful of apex-fan faces wound the wrong way: far too few to flip the sign
of the volume, and quite enough to fail that assertion. The shipped meshes are
already repaired by the exporter; this is the guard for a mesh regenerated by
other means, and it mirrors `mesh_fichera` in
postproc/shape_perturbation_fichera.jl.
"""
function almond_orient(Γ)
    if !CompScienceMeshes.isoriented(Γ)
        @warn "shipped almond mesh is not consistently oriented; repairing " *
              "with CompScienceMeshes.orient -- regenerate the export"
        CompScienceMeshes.orient(Γ)
        @assert CompScienceMeshes.isoriented(Γ) "orient() failed to produce a globally consistent orientation"
    end
    return almond_signed_volume(Γ) < 0 ? -Γ : Γ
end

"""
    almond_check_orientation(Γ)

Assert the mesh is closed, consistently oriented and outward-facing, and
return its enclosed volume.
"""
function almond_check_orientation(Γ)
    @assert CompScienceMeshes.isoriented(Γ) "almond mesh is not consistently oriented"
    vol = almond_signed_volume(Γ)
    @assert vol > 0 "almond mesh is inward-oriented (signed volume $vol)"
    return vol
end

# ---------------------------------------------------------------- the field

struct AlmondField
    W::Matrix{Float64}      # M x 3
    b::Vector{Float64}      # M
    A::Matrix{Float64}      # M x 3
    c::Float64              # sqrt(2/M)
    scale::Float64
    dead::Float64           # cutoff dead length, in units of d (0 => case U)
    ramp::Float64           # cutoff ramp length, in units of d
    x_tip::Float64
    d::Float64
    sup_DV::Float64
    case::String
    ell_name::String
    seed::Int
end

const _ALMOND_INDEX = Ref{Any}(nothing)
const _ALMOND_CACHE = Dict{Tuple{String,String,Int},AlmondField}()

"""
    almond_field_index()

The metadata table of data/almond/fields_index.csv (one row per field), read
once per session. Field COEFFICIENTS are not read here -- there are 140 files
and a driver touches only the handful it needs; see `almond_field`.
"""
function almond_field_index()
    if _ALMOND_INDEX[] === nothing
        path = joinpath(almond_dir(), "fields_index.csv")
        isfile(path) || error("missing $path")
        raw, hdr = readdlm(path, ',', header=true)
        h = Dict(String(strip(string(hdr[i]))) => i for i in eachindex(hdr))
        _ALMOND_INDEX[] = (raw, h)
    end
    return _ALMOND_INDEX[]
end

"""
    almond_field(case, ell_name, seed)

Load one exported field. Cached per session.
"""
function almond_field(case::AbstractString, ell_name::AbstractString, seed::Integer)
    key = (String(case), String(ell_name), Int(seed))
    haskey(_ALMOND_CACHE, key) && return _ALMOND_CACHE[key]
    raw, h = almond_field_index()
    row = 0
    for r in axes(raw, 1)
        if strip(string(raw[r, h["case"]])) == key[1] &&
           strip(string(raw[r, h["ell_name"]])) == key[2] &&
           Int(raw[r, h["seed"]]) == key[3]
            row = r; break
        end
    end
    row == 0 && error("no exported field for case=$(key[1]) " *
                      "ell=$(key[2]) seed=$(key[3])")
    P = readdlm(joinpath(almond_dir(), strip(string(raw[row, h["file"]]))),
                ',', Float64)
    fld = AlmondField(P[:, 1:3], P[:, 4], P[:, 5:7],
                      Float64(raw[row, h["c"]]), Float64(raw[row, h["scale"]]),
                      Float64(raw[row, h["dead"]]), Float64(raw[row, h["ramp"]]),
                      Float64(raw[row, h["x_tip"]]), Float64(raw[row, h["d"]]),
                      Float64(raw[row, h["sup_DV"]]), key[1], key[2], key[3])
    _ALMOND_CACHE[key] = fld
    return fld
end

_hermite(s) = (t = clamp(s, 0.0, 1.0); t * t * (3 - 2t))

"""
    almond_chi(fld, x1)

The C^1 tip cutoff evaluated at the axial coordinate `x1`. Identically 1 when
the field carries no cutoff (case U).
"""
function almond_chi(fld::AlmondField, x1::Real)
    fld.ramp <= 0 && return 1.0
    x0 = fld.x_tip - fld.dead * fld.d
    return _hermite((x0 - x1) / (fld.ramp * fld.d))
end

"""
    almond_displacement(fld, verts, eps)

eps * V(x) at every vertex. Returns a Vector of 3-vectors of the same element
type as `verts`, plus the realised maximum displacement.
"""
function almond_displacement(fld::AlmondField, verts, eps::Real)
    M = size(fld.W, 1)
    T = eltype(verts)
    disp = similar(verts)
    dmax = 0.0
    @inbounds for i in eachindex(verts)
        v = verts[i]
        vx = 0.0; vy = 0.0; vz = 0.0
        for k in 1:M
            ck = cos(fld.W[k, 1] * v[1] + fld.W[k, 2] * v[2] +
                     fld.W[k, 3] * v[3] + fld.b[k])
            vx += fld.A[k, 1] * ck
            vy += fld.A[k, 2] * ck
            vz += fld.A[k, 3] * ck
        end
        w = eps * fld.scale * fld.c * almond_chi(fld, v[1])
        dx, dy, dz = w * vx, w * vy, w * vz
        disp[i] = T(dx, dy, dz)
        dmax = max(dmax, sqrt(dx * dx + dy * dy + dz * dz))
    end
    return disp, dmax
end

"""
    perturb_almond_mesh(Γ0, fld, eps)

Vertex positions move, connectivity does not, so the DOF-alignment
permutation of the Implementation section applies unchanged.
Returns (Γ, maxdisp).
"""
function perturb_almond_mesh(Γ0, fld::AlmondField, eps::Real)
    verts = Γ0.vertices
    T = eltype(verts)
    disp, dmax = almond_displacement(fld, verts, eps)
    newverts = similar(verts)
    @inbounds for i in eachindex(verts)
        newverts[i] = T(verts[i][1] + disp[i][1],
                        verts[i][2] + disp[i][2],
                        verts[i][3] + disp[i][3])
    end
    return Mesh(newverts, Γ0.faces), dmax
end

"""
    almond_levels()

The amplitude ladder, as a Vector of NamedTuples read from
data/almond/levels.csv.
"""
function almond_levels()
    path = joinpath(almond_dir(), "levels.csv")
    isfile(path) || error("missing $path")
    raw, hdr = readdlm(path, ',', header=true)
    h = Dict(String(strip(string(hdr[i]))) => i for i in eachindex(hdr))
    return [(level=Int(raw[r, h["level"]]),
             eps=Float64(raw[r, h["eps_m"]]),
             eps_mm=Float64(raw[r, h["eps_mm"]]),
             lambda_over=Float64(raw[r, h["lambda_over"]]),
             eps_over_h=Float64(raw[r, h["eps_over_h12"]]),
             pct_thick=Float64(raw[r, h["pct_seam_half_thickness"]]))
            for r in axes(raw, 1)]
end

"""
    almond_certificate(fld, eps)

eps * sup|DV|. The drivers require this to stay <= 0.5 and stop if it does
not: an uncertified sample is a specification error, not a sample to drop.
"""
almond_certificate(fld::AlmondField, eps::Real) = eps * fld.sup_DV
